[package]
name = "brainkey"
version = "0.1.4-dev"

[dependencies]
rand = "0.8.3"
rand_chacha = "0.3.0"
rust-crypto = "0.2.36"
termion = "1.5.5"
argparse = "0.2.2"
rustc-serialize = "0.3.24"
hex = "0.4.3"
tiny-bip39 = "0.8.0"
